spring.application.name=netflix

# Render PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://dpg-d8ci059o3t8c739v8a30-a:5432/netflix_7nan?sslmode=require
spring.datasource.username=netflix_7nan_user
spring.datasource.password=2e0G7ire2OXdSMIrC8no8iZq3K7EQmBH

# JPA / Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Cloudinary Configuration
cloudinary.cloud-name=dlm2b9qqr
cloudinary.api-key=319386169641156
cloudinary.api-secret=o-PKKKzbj9Z2dINq0sTnvwRb8FE
spring.sql.init.mode=always

# ??????????? ????? ??????? ???? ???????? ??????????????
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
